# Generated by Django 4.0.4 on 2022-04-27 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_alter_user_follow_count_alter_user_followers_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='follow_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='followers_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
